{% set name = "cellpy" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 968d8ca2b031933d0c0501e791645a4b28b7802c069a1ae7de45507acc510e2f

build:
  number: 1
  skip: true  # [py<310 or py>313]
  entry_points:
    - cellpy=cellpy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python
  host:
    - python
    - pip
    - setuptools >62
  run:
    - python
    - click
    - cookiecutter >=2.1
    - fabric >=3.1
    - hdf5 >=1.14
    - lmfit >=1.2
    - matplotlib-base >=3.7
    - numpy >=1.24
    - openpyxl >=3.1.1
    - pandas >=2.0.1
    - pint >=0.20
    - pip >=23.1
    - pyodbc >=4.0
    - pytables >=3.8
    - python-box >=7.0
    - python-dotenv >=1.0.1
    - rich >=13.5
    - ruamel.yaml >=0.17.21
    - scipy >=1.10.1
    - setuptools >=67.7
    - sqlalchemy >=2.0.11
    - tqdm >=4.65
    - xlrd >=2.0.1
    - ipykernel >=6.29.0
    - ipython >=8.18.1
    - ipywidgets >=8.1.1
    - jupyterlab >=4.1
    - plotly >=5.18.0
    - pygithub >=2.2.0
    - python-kaleido >0.1.0
    - sqlalchemy-access >=2.0.2  # [win]

test:
  imports:
    - cellpy
  commands:
    - cellpy --help

about:
  home: https://github.com/jepegit/cellpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Extract and manipulate data from different battery cell testers.
  description: |
    Extract and manipulate data from different battery cell testers.
  doc_url: https://cellpy.readthedocs.io/
  dev_url: https://github.com/jepegit/cellpy

extra:
  recipe-maintainers:
    - jepegit
